### ISSUE TITLE
[0.74] OSS builds can accidentally using coreutils cp

### ISSUE THREAD

**Issue by cipolleschi** [reactwg/react-native-releases#389]
### Target Branch(es)

0.74

### Link to commit or PR to be picked

https://github.com/facebook/react-native/commit/e0799536ef1b68b98fb772e256d1d72424349008

### Description

This fix will help with issue [#44731](https://github.com/facebook/react-native/issues/44731).

**Comment by Titozzz** [comment]
Picked !

**Comment by najumasad** [comment]
**Possible Solutions for React Native Upgrade Issue**

If you're encountering issues after upgrading React Native from version `0.72.x` to `0.73.x` or `0.74.x`, please consider the following solutions:

**Quick Solution**: Remove the `.xcode.env.local` file located at `app/ios/.xcode.env.local` and attempt to run the project again. The reason for this is that the [React Native upgrade helper](https://react-native-community.github.io/upgrade-helper/?from=0.72.5&to=0.74.3) does not include this file, which might be causing conflicts.

**Additional Information**: A fix for this issue is mentioned in [this GitHub thread](https://github.com/facebook/react-native/issues/44731#:~:text=I%20created%20a%20cherry%20pick%20request%3A%20as%20soon%20as%20we%20prepare%200.74.4%2C%20it%20will%20be%20included!). The fix is expected to be included in React Native version 0.74.4, which should be available soon.

I hope these steps help resolve the issue.
