### ISSUE TITLE
Hermes: fix native stack checking on Android/Bionic 

### ISSUE THREAD

**Issue by tmikov** [reactwg/react-native-releases#588]
### Target Branch(es)

0.76, 0.75

### Link to commit or PR to be picked

https://github.com/facebook/hermes/commit/a5b2bbcf33cf7f475b3d7dce96be2371eb5fda0b

### Description

Fixes stack overflow checking when the guard size is 64KB. This is particularly important for security-oriented distributions like GrapheneOS, that are maintaining binary compatibility with Android. They flagged this to us, and I think it is a good idea to pick it.

(I think I am able to pick this myself into Hermes branches, but I don't want to disturb the official process. However if it would make it easier...)

**Comment by joe-sam** [comment]
You probably need to file separate pick requests  for each of the branch version, and definitely prefix them with a square bracket e.g. [0.7x.] so that the pick is automatically sorted and elevated to notice of  the correct project thread/team.

**Comment by cortinico** [comment]
Also this won't make it to 0.76.0 and will land in 0.76.1

**Comment by joe-sam** [comment]
> there was no indication that square brackets need to be used.

Probably not really necessary and just for human readability and convenience.
The hermes engines are really long overdue to be bumped anyway, due to JSI header divergence, but I understand this is not at all trivial exercise.  an automated workflow every time this happens would be helpful ?

**Comment by tmikov** [comment]
@joe-sam can you elaborate on the divergence? RN and Hermes/Static Hermes are always synchronized in trunk and in every branch cut.

**Comment by joe-sam** [comment]
@tmikov have already elaborated on the divergence.  

https://github.com/reactwg/react-native-releases/issues/579#issuecomment-2418729818

AFAIK from the git diffs compare tags attached to the issue,  the "_required_" hermes engine bump did not occur on the previous changes to the JSI header after the previous cherry-pick 
[Add missing withRuntimeDecorator](https://github.com/reactwg/react-native-releases/issues/349) 
There does not appear to be an intermediate hermes release tag after the changes to the JSI as I would expect. 
The next tag containing the correct headers appears to be aligned to the 0.76 release candidate instead of 0.75.

**Comment by tmikov** [comment]
@joe-sam sorry, I don't understand, probably because I am not very familiar with the RN release process. I am not sure what you mean by a "bump" of Hermes. 

Whenever RN cuts a release, it tags the current (trunk) version of Hermes. As a rule, JSI header changes should only occur at those points, never in cherry-picks (I suppose exceptions can be made for critical bugs).
